/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    CourseCard: typeof import('./src/components/courses/CourseCard.vue')['default']
    CourseInfo: typeof import('./src/components/courses/CourseInfo.vue')['default']
    CourseListElement: typeof import('./src/components/courses/CourseListElement.vue')['default']
    CoursesList: typeof import('./src/components/courses/CoursesList.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentCard: typeof import('./src/components/UserCard.vue')['default']
    UserCard: typeof import('./src/components/UserCard.vue')['default']
  }
}
